### ISSUE TITLE
对这个精悍的程序十分感兴趣,请教下如何修改?

### ISSUE THREAD

**Issue by kkkgo** [gmsj0001/shnu-h3c#1]
您好,我对你项目十分感兴趣,因为njitclient,oh3c什么的在我的路由上面跑不起,就算认证成功,可能由于libpacap或者cpu的原因认证十分缓慢,于是我看到你的精悍简单的h3clite;
## 尝试编译了x86版本运行结果如下:

EAPOL Start
EAP Request Identity
EAP Request MD5
## EAP Failure

njit-client是可以用的,我这里的inode版本是V7.00-0103,对于njit-client的源码我的修改如下:
## auth.c:

const uint8_t BroadcastAddr[6] = {0xff,0xff,0xff,0xff,0xff,0xff}; // 广播MAC地址
const char H3C_VERSION[16]="EN V7.00-0103"; // 华为客户端版本号
## const char H3C_KEY[64]  ="Oly5D62FaE94W7";  // H3C的另一个固定密钥，网友取自MacOSX版本的iNode官方客户端

希望能给予指点,Thanks.

**Comment by gmsj0001** [comment]
因为懒和没有样本测试，代码目前确实只支持SHNU。从描述来看，njit-client能用说明你的学校用的是标准的MD5 challenge，需要从njit里粘相应的代码来。我有时间倒是可以试着适配，但面向空气编程略坑爹，最好能提供pcap的抓包数据作为case参考。
另外，原理上慢和用什么客户端没什么关系，可能是学校的问题。

**Comment by kkkgo** [comment]
http://url.cn/ULWmJB
谢谢你的回复，这个是用wireshark抓的包，参考下。

**Comment by gmsj0001** [comment]
仔细读了一遍njit与xdh3c的代码，和我这边的差别还是比较大的，最近可能没有精力做这么大的改动，故暂时先fork了一份xdh3c试着把libpcap改为raw socket。但我这里没法测试，你可以checkout编译试一试。
https://github.com/godspeed1989/xd-h3c/pull/8

**Comment by kkkgo** [comment]
## 编译成功,X86运行结果:

raw socket创建失败

---

## openwrt-mipsel上运行结果:

等待服务器响应...
等待服务器响应...
等待服务器响应...

**Comment by kkkgo** [comment]
服务器未响应。

**Comment by kkkgo** [comment]
不好意思,在x86上忘记使用root权限执行,使用root权限执行后认证成功,过程如下:
Server MAC is XX:XX:XX:XX:XX:XX
Server: Request [1] Identity!       [responsed]

Server: Request [1] Identity!       [responsed]

Server: Request [2] MD5!            [responsed]

[2] Server: (H3C Data)
6

[2] Server: (H3C Data)
4�����У������ֻ��ѧ�ŵ�У����֤�����ʻ���������Ӫ���˺š����ϣ�����1��8���������ƶ���(这一段是返回的中文消息)

## ------开始运行DHCP服务获取IP------

.........
Server: Request [3] Identity!       [responsed]
........................................................................................................................
Server: Request [4] Identity!       [responsed]
.........................................................................................................................
Server: Request [5] Identity!       [responsed]
........................................................................................................................
Server: Request [6] Identity!       [responsed]
...................................^C(按下Ctrl+C)
接收到退出信号，准备退出。

开始注销。

注销成功。
bye bye!
/////////////////////////////////////////////////////////////////
在openwrt上运行如上面所示,可能是由于系统内核或者CPU的原因,有空我再在其他平台进行测试.

**Comment by gmsj0001** [comment]
话说看这输出不是已经认证成功了么。。。
在openwrt上dhcp客户端是udhcpc不知你改了没，可以参考其他port到openwrt上的fork修改一下。像我们学校还有MAC绑定需要修改路由器MAC地址的说。
这个帖子跑题了先close，请转移到fork的xd-h3c项目下开一个新的～
